# Generated by Django 5.0.7 on 2024-08-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_post',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news_post',
            name='user',
            field=models.CharField(default=1, max_length=5, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
